### ISSUE TITLE
Example fails (on parsing balance type?) 

### ISSUE THREAD

**Issue by jam10o-new** [paritytech/txwrapper#118]
> @jam10o  when i run ./node_modules/.bin/ts-node examples/index.ts to test txwrapper,it tips me:
```
SS58-Encoded Address: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Error: createType(Call):: Struct: failed on 'args':: Balance: Input too large. Found input with 246 bits, expected 128
    at createTypeUnsafe (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/node_modules/@polkadot/types/create/createType.js:68:11)
    at createType (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/node_modules/@polkadot/types/create/createType.js:80:10)
    at TypeRegistry.createType (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/node_modules/@polkadot/types/create/registry.js:187:39)
    at Object.decodeUnsignedTx (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/src/decode/decodeUnsignedTx.ts:58:31)
    at Object.decode (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/src/decode/decode.ts:101:10)
    at /Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/examples/index.ts:122:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Zhangyabo/Develop/WebStormWorkspace/txwrapper/examples/index.ts:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
according to the user they have not changed the example other than the rpc endpoint.

**Comment by amaury1093** [comment]
> other than the rpc endpoint

It might be related to the chain's types, the example assumes types from latest substrate master.

https://github.com/paritytech/txwrapper/blob/cc2fe28350f115884117adf03c60ddd8c0279667/examples/index.ts#L74-L76

I'll still build latest master and double check on my side

**Comment by amaury1093** [comment]
Confirmed, will investigate
