### ISSUE TITLE
Can not verify signature when using ecdsa keys

### ISSUE THREAD

**Issue by anhcao142** [paritytech/txwrapper#251]
Get `Expected signature with 65 bytes, 66 found instead` when trying to verify the signature with a transfer tx payload. I think it related to the extra TYPE_PREFIX byte prepend to signature after signing. Here is my example code:

```javascript
const api = require('@polkadot/api');
const util = require('@polkadot/util');
const fetch = require('node-fetch');
const txWrapper = require('@substrate/txwrapper');
const utilCrypto = require('@polkadot/util-crypto');

const url = 'http://localhost:8080';

async function main() {
  // Api is provided by subtrate-api-sidecar, so you might want to input your own material data
  const material = await (await fetch(`${url}/transaction/material/`)).json();
  const keyring = new api.Keyring();
  const alice = keyring.addFromUri('//Alice', { name: 'Alice' }, 'ecdsa');
  const registry = txWrapper.getRegistry(material.chainName, material.specName, Number(material.specVersion));
  const unsigned = txWrapper.methods.balances.transfer({
    value: '10000',
    dest: '5DpGPTju2gHJKo8cjWRGwzyUPKHBkGVm7d9HH6XUyn5qi1p6', // random address
  }, {
    tip: 0,
    nonce: 2,
    address: alice.address,
    eraPeriod: 10000,
    blockNumber: Number(material.at.height),
    blockHash: material.at.hash,
    genesisHash: material.genesisHash,
    metadataRpc: material.metadata,
    specVersion: Number(material.specVersion),
    transactionVersion: Number(material.txVersion),
  }, {
    registry,
    metadataRpc: material.metadata,
  });

  const signing = txWrapper.createSigningPayload(unsigned, { registry });
  const { signature } = registry.createType('ExtrinsicPayload', signing, { version: 4 }).sign(alice);
  console.log(alice.verify(util.u8aToU8a(signing), util.u8aToU8a(signature)));
}

main().catch(console.log);

```

And here is the error:
```sh
Error: Expected signature with 65 bytes, 66 found instead
    at assert (/Users/admin/test/node_modules/@polkadot/util/assert.js:34:11)
    at secp256k1Verify (/Users/admin/test/node_modules/@polkadot/util-crypto/secp256k1/verify.js:30:20)
    at Object.ecdsa (/Users/admin/test/node_modules/@polkadot/keyring/pair/index.js:52:55)
    at Object.verify (/Users/admin/test/node_modules/@polkadot/keyring/pair/index.js:199:54)
    at main (/Users/admin/test/example.js:35:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by emostov** [comment]
Thank you for the example code. 

I could not find any docs specific to this, but looking at the polkadot-js source code, you are correct in that it is related to the type prefix prepended to the signature. For the signature you will need to remove the type prefix. 

The one other thing that you will need to change is the `message` you are verifying the signature with; in this  case you need the scale encoded extrinsic payload modified such that the length prefix is removed from the `method` property.

Below I have an example script similar to yours that demonstrates how to get the correct `signature` and `message` for verification.

```typescript
import * as api from '@polkadot/api';
import * as util from '@polkadot/util';
import * as txwrapper from '@substrate/txwrapper';
import axios from 'axios';

const url = 'http://localhost:8080';

async function main() {
	const material = (await axios.get(`${url}/transaction/material`))
		.data as Record<string, any>;

	const keyring = new api.Keyring();
	const alice = keyring.addFromUri('//Alice', { name: 'Alice' }, 'ecdsa');

	const registry = txwrapper.getRegistry(
		material.chainName,
		material.specName,
		Number(material.specVersion),
		material.metadata
	);

	const unsigned = txwrapper.methods.balances.transfer(
		{
			value: '10000',
			dest: '5DpGPTju2gHJKo8cjWRGwzyUPKHBkGVm7d9HH6XUyn5qi1p6', // random address
		},
		{
			tip: 0,
			nonce: 2,
			address: alice.address,
			eraPeriod: 10000,
			blockNumber: Number(material.at.height),
			blockHash: material.at.hash,
			genesisHash: material.genesisHash,
			metadataRpc: material.metadata,
			specVersion: Number(material.specVersion),
			transactionVersion: Number(material.txVersion),
		},
		{
			registry,
			metadataRpc: material.metadata,
		}
	);

	const signingPayload = txwrapper.createSigningPayload(unsigned, {
		registry,
	});
	const extrinsicPayload = registry.createType(
		'ExtrinsicPayload',
		signingPayload,
		{
			version: 4,
		}
	);

	const { signature } = extrinsicPayload.sign(alice);
	// The above line is equivalent to:
	const exampleSignature = alice.sign(
		extrinsicPayload.toU8a({ method: true }),
		{ withType: true }
	);
	console.info(
		'\n`signature` is equivalent to `exampleSignature`: ',
		util.u8aToHex(exampleSignature) === signature
	);

	// As mentioned in the comment within the `ExtrinsincPayload.sign` method (see link 2), the actual payload that is
	// signed is different from `ExtrinsincPayload.toU8a` because it does not have the length of the `method`
	// property included in the encoding
	const actualPayloadThatWasSigned = extrinsicPayload.toU8a({ method: true });

	// slice out the type prefix that gets concatenated when signing (see links 1 & 2)
	const signatureWithTypePrefixRemoved = util.hexToU8a(signature).slice(1);

	console.info(
		'\nThe signature is valid for the payload: ',
		alice.verify(actualPayloadThatWasSigned, signatureWithTypePrefixRemoved)
	);
}

main().catch(console.log);
```

Here are links referenced in the script comments:
 1) Type prefix concatenation in key pair signing: https://github.com/polkadot-js/common/blob/master/packages/keyring/src/pair/index.ts#L171
 2) Option passed to use type prefix when signing extrinsic payload (see withType) and you can see the actuall payload that was signed: https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L93

**Comment by anhcao142** [comment]
Thank you for the detail explanation
